spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://<host>:5432/<db_name>
    username: <username>
    password: <password>
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect